### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by ramanshah** [milseman/yaml-light#3]
I am a Haskell beginner (but experienced programmer) and am trying to write my first Haskell programs that aren't book examples or exercises. I am struggling more than I thought I would. A particular annoyance has been the bulk of dependencies for the `aeson` -> `yaml` route - the first `stack build` takes something like 10 minutes, and linking a program of hello-world complexity takes nearly 10 seconds. Which brings me here...

I think "quickstart" documentation for `yaml-light` would be extremely helpful. For example, in Prelude, how would one parse a simple YAML file to the point where one could manipulate its data in Haskell? I'm working this out right now from a variety of sources and experimentation.

I may be able to contribute a quickstart once I grok enough of the details. If so, what's your interest level, and where should such a quickstart live?

**Comment by milseman** [comment]
There's:
```
-- | Parse a regular Haskell string
  parseYaml :: String -> IO YamlLight
```
and
```
  -- | Given a file name, parse contents of file
  parseYamlFile :: String -> IO YamlLight
```

These result in an IO YamlLight, which is a simple ADT representing either a mapping, a sequence, a string, or nil.

**Comment by ramanshah** [comment]
Thanks much for the pointer! I think that's the first part of a good quickstart. So would you like a quickstart in your repo, and if so, what form should it take? For example, I could send a PR adding a quickstart to `README.md` showing how to round-trip a YAML string after applying a simple modification to the data structure. If not, I'll put one together elsewhere.

I think I was imprecise in my original post: I think the harder part for a beginner will be what follows the load step. Once I have `yaml-light`'s ADT, now what? Typical use-cases are to render the YAML data in a different form; use the YAML data to configure program behavior; or re-marshal the YAML after modifying the data within the program. Applying business logic to arbitrary nested data verges on trivial in a dynamic language (say a Python or Ruby where `y['foo']['a'][1] == 2`); the statically typed equivalent is much less familiar (at least to me).

**Comment by milseman** [comment]
The usage of the ADT is inherently domain-specific. Yaml is a convenient but minimally structured format for arbitrary data and relations. This package tries to provide programatic access to the data by reading the strings into structured ADTs. But, it doesn't provide any kind of business logic layer, schemas, ORM mappings, or any such stuff. 

The only real generally applicable examples would similar to the tests at the bottom of the file.

**Comment by ramanshah** [comment]
OK, thanks.
